AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Send Email from rentcheck.ninja
Resources:
  serverlessmailer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: .
      Description: Send Email from rentcheck.ninja
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::879189804904:role/west-mailer'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /
            Method: POST
